apiVersion: apps/v1
kind: Deployment
metadata:
  name: Health_care-eta-deploy
  labels:
    app: Health_care-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Health_care-eta-app
  template:
    metadata:
      labels:
        app: Health_care-eta-app
    spec:
      containers:
      - name: Health_care-eta-container
        image: bsvk38/health-care-eta-app:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: Health_care-eta-np-service
  labels:
    app: Health_care-eta-app
spec:
  selector:
    app: Health_care-eta-app

  type: NodePort
  ports:
  - nodePort: 31030
    port: 8082
    targetPort: 8081
