apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-eta-deploy
  labels:
    app: healthcare-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-eta-app
  template:
    metadata:
      labels:
        app: healthcare-eta-app
   spec:
      nodeSelector:
        kubernetes.io/hostname: worker-node1
      containers:
      - name: healthcare-eta-container
        image: bsvk38/health-care-eta-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-eta-np-service
  labels:
    app: healthcare-eta-app
spec:
  selector:
    app: healthcare-eta-app
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8080
    nodePort: 31028
